package lt.vu.mybatis.dao;

import java.util.List;
import lt.vu.mybatis.model.Reservation;
import org.mybatis.cdi.Mapper;

@Mapper
public interface ReservationMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.RESERVATION
     *
     * @mbg.generated Mon Apr 20 21:45:59 EEST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.RESERVATION
     *
     * @mbg.generated Mon Apr 20 21:45:59 EEST 2020
     */
    int insert(Reservation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.RESERVATION
     *
     * @mbg.generated Mon Apr 20 21:45:59 EEST 2020
     */
    Reservation selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.RESERVATION
     *
     * @mbg.generated Mon Apr 20 21:45:59 EEST 2020
     */
    List<Reservation> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.RESERVATION
     *
     * @mbg.generated Mon Apr 20 21:45:59 EEST 2020
     */
    int updateByPrimaryKey(Reservation record);
}