package lt.vu.mybatis.dao;

import java.util.List;
import lt.vu.mybatis.model.Roomtype;
import org.mybatis.cdi.Mapper;

@Mapper
public interface RoomtypeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.ROOMTYPE
     *
     * @mbg.generated Mon Apr 20 21:45:59 EEST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.ROOMTYPE
     *
     * @mbg.generated Mon Apr 20 21:45:59 EEST 2020
     */
    int insert(Roomtype record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.ROOMTYPE
     *
     * @mbg.generated Mon Apr 20 21:45:59 EEST 2020
     */
    Roomtype selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.ROOMTYPE
     *
     * @mbg.generated Mon Apr 20 21:45:59 EEST 2020
     */
    List<Roomtype> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.ROOMTYPE
     *
     * @mbg.generated Mon Apr 20 21:45:59 EEST 2020
     */
    int updateByPrimaryKey(Roomtype record);
}