package lt.vu.mybatis.model;

public class Client {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.CLIENT.ID
     *
     * @mbg.generated Mon Apr 20 21:45:59 EEST 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.CLIENT.EMAIL
     *
     * @mbg.generated Mon Apr 20 21:45:59 EEST 2020
     */
    private String email;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.CLIENT.NAME
     *
     * @mbg.generated Mon Apr 20 21:45:59 EEST 2020
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.CLIENT.PHONE_NR
     *
     * @mbg.generated Mon Apr 20 21:45:59 EEST 2020
     */
    private String phoneNr;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.CLIENT.SURNAME
     *
     * @mbg.generated Mon Apr 20 21:45:59 EEST 2020
     */
    private String surname;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.CLIENT.ID
     *
     * @return the value of PUBLIC.CLIENT.ID
     *
     * @mbg.generated Mon Apr 20 21:45:59 EEST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.CLIENT.ID
     *
     * @param id the value for PUBLIC.CLIENT.ID
     *
     * @mbg.generated Mon Apr 20 21:45:59 EEST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.CLIENT.EMAIL
     *
     * @return the value of PUBLIC.CLIENT.EMAIL
     *
     * @mbg.generated Mon Apr 20 21:45:59 EEST 2020
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.CLIENT.EMAIL
     *
     * @param email the value for PUBLIC.CLIENT.EMAIL
     *
     * @mbg.generated Mon Apr 20 21:45:59 EEST 2020
     */
    public void setEmail(String email) {
        this.email = email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.CLIENT.NAME
     *
     * @return the value of PUBLIC.CLIENT.NAME
     *
     * @mbg.generated Mon Apr 20 21:45:59 EEST 2020
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.CLIENT.NAME
     *
     * @param name the value for PUBLIC.CLIENT.NAME
     *
     * @mbg.generated Mon Apr 20 21:45:59 EEST 2020
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.CLIENT.PHONE_NR
     *
     * @return the value of PUBLIC.CLIENT.PHONE_NR
     *
     * @mbg.generated Mon Apr 20 21:45:59 EEST 2020
     */
    public String getPhoneNr() {
        return phoneNr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.CLIENT.PHONE_NR
     *
     * @param phoneNr the value for PUBLIC.CLIENT.PHONE_NR
     *
     * @mbg.generated Mon Apr 20 21:45:59 EEST 2020
     */
    public void setPhoneNr(String phoneNr) {
        this.phoneNr = phoneNr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.CLIENT.SURNAME
     *
     * @return the value of PUBLIC.CLIENT.SURNAME
     *
     * @mbg.generated Mon Apr 20 21:45:59 EEST 2020
     */
    public String getSurname() {
        return surname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.CLIENT.SURNAME
     *
     * @param surname the value for PUBLIC.CLIENT.SURNAME
     *
     * @mbg.generated Mon Apr 20 21:45:59 EEST 2020
     */
    public void setSurname(String surname) {
        this.surname = surname;
    }
}