package lt.vu.mybatis.model;

import lombok.Getter;
import lombok.Setter;

import java.util.Date;
import java.util.List;

public class Reservation {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.RESERVATION.ID
     *
     * @mbg.generated Mon Apr 20 21:45:59 EEST 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.RESERVATION.DATE_FROM
     *
     * @mbg.generated Mon Apr 20 21:45:59 EEST 2020
     */
    private Date dateFrom;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.RESERVATION.DATE_TO
     *
     * @mbg.generated Mon Apr 20 21:45:59 EEST 2020
     */
    private Date dateTo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.RESERVATION.IS_CHECKED_IN
     *
     * @mbg.generated Mon Apr 20 21:45:59 EEST 2020
     */
    private Boolean isCheckedIn;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.RESERVATION.CLIENT_ID
     *
     * @mbg.generated Mon Apr 20 21:45:59 EEST 2020
     */
    private Integer clientId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.RESERVATION.ROOM_ID
     *
     * @mbg.generated Mon Apr 20 21:45:59 EEST 2020
     */
    private Integer roomId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.RESERVATION.ID
     *
     * @return the value of PUBLIC.RESERVATION.ID
     *
     * @mbg.generated Mon Apr 20 21:45:59 EEST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.RESERVATION.ID
     *
     * @param id the value for PUBLIC.RESERVATION.ID
     *
     * @mbg.generated Mon Apr 20 21:45:59 EEST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.RESERVATION.DATE_FROM
     *
     * @return the value of PUBLIC.RESERVATION.DATE_FROM
     *
     * @mbg.generated Mon Apr 20 21:45:59 EEST 2020
     */
    public Date getDateFrom() {
        return dateFrom;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.RESERVATION.DATE_FROM
     *
     * @param dateFrom the value for PUBLIC.RESERVATION.DATE_FROM
     *
     * @mbg.generated Mon Apr 20 21:45:59 EEST 2020
     */
    public void setDateFrom(Date dateFrom) {
        this.dateFrom = dateFrom;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.RESERVATION.DATE_TO
     *
     * @return the value of PUBLIC.RESERVATION.DATE_TO
     *
     * @mbg.generated Mon Apr 20 21:45:59 EEST 2020
     */
    public Date getDateTo() {
        return dateTo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.RESERVATION.DATE_TO
     *
     * @param dateTo the value for PUBLIC.RESERVATION.DATE_TO
     *
     * @mbg.generated Mon Apr 20 21:45:59 EEST 2020
     */
    public void setDateTo(Date dateTo) {
        this.dateTo = dateTo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.RESERVATION.IS_CHECKED_IN
     *
     * @return the value of PUBLIC.RESERVATION.IS_CHECKED_IN
     *
     * @mbg.generated Mon Apr 20 21:45:59 EEST 2020
     */
    public Boolean getIsCheckedIn() {
        return isCheckedIn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.RESERVATION.IS_CHECKED_IN
     *
     * @param isCheckedIn the value for PUBLIC.RESERVATION.IS_CHECKED_IN
     *
     * @mbg.generated Mon Apr 20 21:45:59 EEST 2020
     */
    public void setIsCheckedIn(Boolean isCheckedIn) {
        this.isCheckedIn = isCheckedIn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.RESERVATION.CLIENT_ID
     *
     * @return the value of PUBLIC.RESERVATION.CLIENT_ID
     *
     * @mbg.generated Mon Apr 20 21:45:59 EEST 2020
     */
    public Integer getClientId() {
        return clientId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.RESERVATION.CLIENT_ID
     *
     * @param clientId the value for PUBLIC.RESERVATION.CLIENT_ID
     *
     * @mbg.generated Mon Apr 20 21:45:59 EEST 2020
     */
    public void setClientId(Integer clientId) {
        this.clientId = clientId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.RESERVATION.ROOM_ID
     *
     * @return the value of PUBLIC.RESERVATION.ROOM_ID
     *
     * @mbg.generated Mon Apr 20 21:45:59 EEST 2020
     */
    public Integer getRoomId() {
        return roomId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.RESERVATION.ROOM_ID
     *
     * @param roomId the value for PUBLIC.RESERVATION.ROOM_ID
     *
     * @mbg.generated Mon Apr 20 21:45:59 EEST 2020
     */
    public void setRoomId(Integer roomId) {
        this.roomId = roomId;
    }

    //Added manually
    @Getter @Setter
    private Client client;

    @Getter @Setter
    private Room room;

    @Getter @Setter
    private List<AditionalRequest> aditionalRequests;
}