package lt.vu.mybatis.model;

public class ReservationAditionalRequest {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.RESERVATION_ADITIONAL_REQUEST.RESERVATION_ID
     *
     * @mbg.generated Mon Apr 20 22:14:20 EEST 2020
     */
    private Integer reservationId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.RESERVATION_ADITIONAL_REQUEST.ADITIONALREQUESTS_ID
     *
     * @mbg.generated Mon Apr 20 22:14:20 EEST 2020
     */
    private Integer aditionalrequestsId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.RESERVATION_ADITIONAL_REQUEST.RESERVATION_ID
     *
     * @return the value of PUBLIC.RESERVATION_ADITIONAL_REQUEST.RESERVATION_ID
     *
     * @mbg.generated Mon Apr 20 22:14:20 EEST 2020
     */
    public Integer getReservationId() {
        return reservationId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.RESERVATION_ADITIONAL_REQUEST.RESERVATION_ID
     *
     * @param reservationId the value for PUBLIC.RESERVATION_ADITIONAL_REQUEST.RESERVATION_ID
     *
     * @mbg.generated Mon Apr 20 22:14:20 EEST 2020
     */
    public void setReservationId(Integer reservationId) {
        this.reservationId = reservationId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.RESERVATION_ADITIONAL_REQUEST.ADITIONALREQUESTS_ID
     *
     * @return the value of PUBLIC.RESERVATION_ADITIONAL_REQUEST.ADITIONALREQUESTS_ID
     *
     * @mbg.generated Mon Apr 20 22:14:20 EEST 2020
     */
    public Integer getAditionalrequestsId() {
        return aditionalrequestsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.RESERVATION_ADITIONAL_REQUEST.ADITIONALREQUESTS_ID
     *
     * @param aditionalrequestsId the value for PUBLIC.RESERVATION_ADITIONAL_REQUEST.ADITIONALREQUESTS_ID
     *
     * @mbg.generated Mon Apr 20 22:14:20 EEST 2020
     */
    public void setAditionalrequestsId(Integer aditionalrequestsId) {
        this.aditionalrequestsId = aditionalrequestsId;
    }
}