package lt.vu.mybatis.model;

public class Roomtype {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.ROOMTYPE.ID
     *
     * @mbg.generated Mon Apr 20 21:45:59 EEST 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.ROOMTYPE.NIGHT_PRICE
     *
     * @mbg.generated Mon Apr 20 21:45:59 EEST 2020
     */
    private Integer nightPrice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.ROOMTYPE.SIZE
     *
     * @mbg.generated Mon Apr 20 21:45:59 EEST 2020
     */
    private Integer size;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.ROOMTYPE.TYPE
     *
     * @mbg.generated Mon Apr 20 21:45:59 EEST 2020
     */
    private String type;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.ROOMTYPE.ID
     *
     * @return the value of PUBLIC.ROOMTYPE.ID
     *
     * @mbg.generated Mon Apr 20 21:45:59 EEST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.ROOMTYPE.ID
     *
     * @param id the value for PUBLIC.ROOMTYPE.ID
     *
     * @mbg.generated Mon Apr 20 21:45:59 EEST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.ROOMTYPE.NIGHT_PRICE
     *
     * @return the value of PUBLIC.ROOMTYPE.NIGHT_PRICE
     *
     * @mbg.generated Mon Apr 20 21:45:59 EEST 2020
     */
    public Integer getNightPrice() {
        return nightPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.ROOMTYPE.NIGHT_PRICE
     *
     * @param nightPrice the value for PUBLIC.ROOMTYPE.NIGHT_PRICE
     *
     * @mbg.generated Mon Apr 20 21:45:59 EEST 2020
     */
    public void setNightPrice(Integer nightPrice) {
        this.nightPrice = nightPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.ROOMTYPE.SIZE
     *
     * @return the value of PUBLIC.ROOMTYPE.SIZE
     *
     * @mbg.generated Mon Apr 20 21:45:59 EEST 2020
     */
    public Integer getSize() {
        return size;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.ROOMTYPE.SIZE
     *
     * @param size the value for PUBLIC.ROOMTYPE.SIZE
     *
     * @mbg.generated Mon Apr 20 21:45:59 EEST 2020
     */
    public void setSize(Integer size) {
        this.size = size;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.ROOMTYPE.TYPE
     *
     * @return the value of PUBLIC.ROOMTYPE.TYPE
     *
     * @mbg.generated Mon Apr 20 21:45:59 EEST 2020
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.ROOMTYPE.TYPE
     *
     * @param type the value for PUBLIC.ROOMTYPE.TYPE
     *
     * @mbg.generated Mon Apr 20 21:45:59 EEST 2020
     */
    public void setType(String type) {
        this.type = type;
    }
}