package lt.vu.mybatis.model;

import lombok.Getter;
import lombok.Setter;

public class Room {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.ROOM.ID
     *
     * @mbg.generated Mon Apr 20 21:45:59 EEST 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.ROOM.NUMBER
     *
     * @mbg.generated Mon Apr 20 21:45:59 EEST 2020
     */
    private Integer number;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.ROOM.ROOM_TYPE_ID
     *
     * @mbg.generated Mon Apr 20 21:45:59 EEST 2020
     */
    private Integer roomTypeId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.ROOM.ID
     *
     * @return the value of PUBLIC.ROOM.ID
     *
     * @mbg.generated Mon Apr 20 21:45:59 EEST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.ROOM.ID
     *
     * @param id the value for PUBLIC.ROOM.ID
     *
     * @mbg.generated Mon Apr 20 21:45:59 EEST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.ROOM.NUMBER
     *
     * @return the value of PUBLIC.ROOM.NUMBER
     *
     * @mbg.generated Mon Apr 20 21:45:59 EEST 2020
     */
    public Integer getNumber() {
        return number;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.ROOM.NUMBER
     *
     * @param number the value for PUBLIC.ROOM.NUMBER
     *
     * @mbg.generated Mon Apr 20 21:45:59 EEST 2020
     */
    public void setNumber(Integer number) {
        this.number = number;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.ROOM.ROOM_TYPE_ID
     *
     * @return the value of PUBLIC.ROOM.ROOM_TYPE_ID
     *
     * @mbg.generated Mon Apr 20 21:45:59 EEST 2020
     */
    public Integer getRoomTypeId() {
        return roomTypeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.ROOM.ROOM_TYPE_ID
     *
     * @param roomTypeId the value for PUBLIC.ROOM.ROOM_TYPE_ID
     *
     * @mbg.generated Mon Apr 20 21:45:59 EEST 2020
     */
    public void setRoomTypeId(Integer roomTypeId) {
        this.roomTypeId = roomTypeId;
    }

    //Added manually
    @Getter @Setter
    private Roomtype roomtype;
}